name: CI
on:
 push:
  branch: ["main"]

jobs:
  build:
   runs-build: "ubuntu-latest"

   steps:
    - name : Check out the code
      uses: actions/checkout@v6

    - name : node js setup 
      uses : actions/setup-node@v6

    - name : install 
      run : npm install

    - name : runs 
      run : node server.js
